// <auto-generated />
using CommerceApp.Models.DbFirst.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CommerceApp.Models.DbFirst.Migrations
{
    [DbContext(typeof(MyShopContext))]
    [Migration("20190201134343_DbMigrations")]
    partial class DbMigrations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CommerceApp.Models.DbFirst.Models.Categories", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("CommerceApp.Models.DbFirst.Models.ProductAttributes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code");

                    b.Property<string>("ISOCode");

                    b.HasKey("Id");

                    b.ToTable("ProductAttributes");
                });

            modelBuilder.Entity("CommerceApp.Models.DbFirst.Models.Products", b =>
                {
                    b.Property<int>("PKID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CID");

                    b.Property<string>("ImageUrl")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ProductName")
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20)
                        .HasDefaultValue("Machine");

                    b.Property<decimal>("Price");

                    b.Property<int>("ProductAttributeId");

                    b.HasKey("PKID");

                    b.HasIndex("CID");

                    b.HasIndex("ProductAttributeId")
                        .IsUnique();

                    b.ToTable("Product");
                });

            modelBuilder.Entity("CommerceApp.Models.DbFirst.Models.Products", b =>
                {
                    b.HasOne("CommerceApp.Models.DbFirst.Models.Categories", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CommerceApp.Models.DbFirst.Models.ProductAttributes", "ProductAtrribute")
                        .WithOne("Product")
                        .HasForeignKey("CommerceApp.Models.DbFirst.Models.Products", "ProductAttributeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
